## Crear una lista

A diferencia de los tipos de datos *int*, *bool*, etc., una lista es un tipo de datos compuesto; dónde puedes agrupar valores:

```python
a = "is"  
b = "nice"  
my_list = ["my", "list", a, b]
```

Después de medir la altura de su familia, decide recopilar información sobre la casa en la que vive. Las áreas de las diferentes partes de su casa se almacenan en variables separadas por ahora, como se muestra arriba.

**Actividad**

* Cree una lista llamada *areas* que contenga el área del pasillo (hall), la cocina (kit), la sala de estar (liv), el dormitorio (bed) y el baño (bath), en este orden. Utiliza las variables predefinidas.

* Imprime *areas* con la función print().

In [2]:
# variables de area (en metros cuadrados)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Crea lista de areas
areas = [hall, kit, liv, bed, bath]

# Imprime areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


## Crea una lista con diferentes tipos

Una lista puede contener cualquier tipo de dato de Python. Aunque no es realmente común, una lista también puede contener una combinación de tipos de datos de Python que incluyen cadenas, flotantes, booleanos, etc.

La impresión del ejercicio anterior no fue realmente satisfactoria. Es solo una lista de números que representan las áreas, pero no puede saber qué área corresponde a qué parte de su casa.

El código de abajo es el comienzo de una solución. Para algunas de las áreas, el nombre de la habitación correspondiente ya se encuentra al frente. ¡Presta atención aquí! "bathroom"es una cadena, mientras que bath una variable que representa el flotante 9.50 que especificó anteriormente.

Termine la línea de código que crea la lista de areas. Cree la lista de modo que primero contenga el nombre de cada habitación como una cadena y luego su área. En otras palabras, añadir los strings "hallway", "kitchen" y "bedroom"en los lugares apropiados.

Imprimir de areasnuevo; ¿Es la impresión más informativa esta vez?

In [4]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = [, hall, , kit, "living room", liv, "bedroom", bed, , bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


## Selecciona la lista válida

Una lista puede contener cualquier tipo de Python. Pero una lista en sí también es de tipo Python. ¡Eso significa que una lista también puede contener una lista! Python se está volviendo cada vez más funky, pero no temas, solo recuerda la sintaxis de la lista:

my_list = [el1, el2, el3]

Prube las siguientes líneas de código Python y concluya si son formas validas de lista

A. [1, 3, 4, 2]  
B. [[1, 2, 3], [4, 5, 7]]  
C. [1 + 2, "a" * 5, 3]

## Lista de listas

Como científico de datos, a menudo estará tratando con muchos datos, y tendrá sentido agrupar algunos de estos datos.

En lugar de crear una lista plana que contenga cadenas y flotantes, que represente los nombres y áreas de las habitaciones de su casa, puede crear una lista de listas.

No se confunda aquí: "hallway"es una cadena, mientras que halles una variable que representa el flotante 11.25 que especificó anteriormente.

* Termine la lista de listas para que también contenga los datos del dormitorio y el baño. ¡Asegúrese de ingresarlos en orden!
* Imprimir house; ¿Tiene más sentido esta forma de estructurar sus datos?
* Imprime el tipo de house. ¿Sigues lidiando con una lista?

In [8]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0]]
<class 'list'>


# Subconjunto de listas

## Subconjunto y conquistar

Subconjunto de listas de Python es pan comido. Tome el ejemplo de código a continuación, que crea una lista x y luego selecciona "b". Recuerde que este es el segundo elemento, por lo que tiene el índice 1. También puede usar la indexación negativa.

x = ["a", "b", "c", "d"]  
x[1]  
x[-3] # same result!  

¿Recuerdas la areaslista de antes, que contiene cadenas y flotantes? Su definición ya está en el guión. ¿Puedes agregar el código correcto para hacer algunos subconjuntos de Python?

* Imprima el segundo elemento de la areaslista (tiene el valor 11.25).
* Subconjunto e imprime el último elemento de areas, ser 9.50. ¡Usar un índice negativo tiene sentido aquí!
* Seleccione el número que representa el área de la sala de estar ( 20.0) e imprímalo.

In [6]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


## Subconjunto y calcular

Después de extraer los valores de una lista, puede usarlos para realizar cálculos adicionales. Tome este ejemplo, donde de x se extrae el segundo y cuarto elemento de una lista. Las cadenas que resultan se unen usando el operador + :


In [7]:
x = ["a", "b", "c", "d"]

print(x[1] + x[3])

bd


**Actividad**
* Usando una combinación de subconjunto de listas y asignación de variables, cree una nueva variable eat_sleep_areaque contenga la suma del área de la cocina y el área del dormitorio.
* Imprime la nueva variable eat_sleep_area.

In [8]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3]+ areas[-3]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


## Tajando y cortando

Seleccionar valores individuales de una lista es solo una parte de la historia. También es posible dividir su lista, lo que significa seleccionar varios elementos de su lista. Use la siguiente sintaxis:

my_list[start:end]

El start índice se incluirá, mientras que el end índice no .

El siguiente ejemplo de código muestra un ejemplo. Se selecciona una lista con "b" y "c", correspondiente a los índices 1 y 2, de una lista x:



In [9]:
x = ["a", "b", "c", "d"]  
x[1:3]  

#Los elementos con índice 1 y 2 están incluidos, mientras que el elemento con índice 3 no lo está.

['b', 'c']

**Actividad**
* Use la división para crear una lista downstairs que contenga los primeros 6 elementos de areas.
* Haga algo similar para crear una nueva variable upstairs, que contenga los últimos 4 elementos de areas.
* Imprime ambos downstairsy upstairsusando print().

In [10]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


## Rebanar y cortar en cubitos (2)

En el video, Hugo primero discutió la sintaxis en la que especifica dónde comenzar y finalizar la porción de su lista:

my_list[begin:end]

Sin embargo, también es posible no especificar estos índices. Si no especifica el beginíndice, Python descubre que desea comenzar su segmento al comienzo de su lista. Si no especifica el endíndice, el segmento irá hasta el último elemento de su lista. Para experimentar con esto, pruebe los siguientes comandos en el Shell de IPython:

In [12]:
x = ["a", "b", "c", "d"]

print(x[:2])
print(x[2:])
print(x[:])

['a', 'b']
['c', 'd']
['a', 'b', 'c', 'd']


**Actividad**

* Crear de downstairsnuevo, como los primeros 6elementos de areas. Esta vez, simplifique el corte omitiendo el beginíndice.
* Crear de upstairsnuevo, como los últimos 4elementos de areas. Esta vez, simplifique el corte omitiendo el endíndice.

In [7]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Alternative slicing to create downstairs
downstairs = areas[:6]

# Alternative slicing to create upstairs
upstairs = areas[-4:]

## Subconjunto de listas de listas

Viste antes que una lista de Python puede contener prácticamente cualquier cosa; incluso otras listas! Para subconjuntar listas de listas, puede usar la misma técnica que antes: corchetes. Pruebe los comandos en el siguiente ejemplo de código en las celdas de jupyter:

x = [["a", "b", "c"],  
     ["d", "e", "f"],  
     ["g", "h", "i"]]  
x[2][0]  
x[2][:2]

x[2] da como resultado una lista que puede volver a subconjuntar agregando corchetes adicionales.

¿Qué tipo de datos volverá house[-1][1]?, la lista de listas que creó anteriormente.

20.0