## Recorrer una lista

**fam = [1.73, 1.68, 1.71, 1.89]  
for height in fam :   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    print(height)**

Como de costumbre, simplemente tiene que indentar el código con 4 espacios para indicarle a Python qué código debe ejecutarse en el bucle for.

La variable *areas*, que contiene el área de diferentes habitaciones en su casa, ya está definida.

**Actividad**

* Escriba un bucle for que repita todos los elementos de la lista *areas* e imprima cada elemento por separado.

In [1]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for room in areas:
    print(room)

11.25
18.0
20.0
10.75
9.5


## Índices y valores (1)

El uso de un bucle for para iterar sobre una lista solo le da acceso a cada elemento de la lista en cada ejecución, uno tras otro. Si también desea acceder a la información del índice, puede ubicar el elemento de la lista sobre el que está iterando enumerate().

Como ejemplo, eche un vistazo a cómo forse convirtió el bucle del video:

**fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam) :
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    print("person " + str(index) + ": " + str(height))**

**Actividad**

* Adapte el bucle *for* en el código de muestra para usar **enumerate()** y use dos variables iteradoras.
* Actualice la declaración **print()** para que en cada ejecución, "*room a: b*" se imprima una línea del formulario , donde **a** es el índice del elemento de la lista y **b** es el elemento de la lista real, es decir, el área. Asegúrese de imprimir esta cadena exacta, con el espacio correcto.

In [2]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change for loop to use enumerate() and update print()
for a,b in enumerate(areas) :
    print("room " + str(a) + ": " + str(b))

room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5


## Índices y valores (2)

Para los no programadores, *room 0: 11.25* es extraño. ¿No sería mejor si el conteo comenzara en 1?

**Actividad**

* Adapte la función **print()** en el bucle *for* para que la primera impresión se convierta "*room 1: 11.25*", la segunda "*room 2: 18.0*" y así sucesivamente.

In [3]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for index, area in enumerate(areas) :
    print("room " + str(index+1) + ": " + str(area))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5


## Recorrer la lista de listas

¿Recuerdas la variable house del curso de Introducción a Python? Echa un vistazo a su definición. Básicamente es una lista de listas, donde cada sublista contiene el nombre y el área de una habitación en su casa.

¡Depende de usted construir un bucle for desde cero esta vez!

**Actividad**

* Escriba un bucle for que pase por cada sublista de *house* e imprima *the x is y sqm*, donde **x** es el nombre de la habitación e **y** es el área de la habitación.

In [4]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch
for list in house:
    print("the " + list[0] + " is " + str(list[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm
